#!/usr/bin/env bash

# Get existing dashboards and prep for terraform

# Issues with JSON copied from Google console -> dashboard editor -> json editor
#   json is not same as what is stored. It is generated by the UI

# Use gcloud or API to download dashboards

project=$1

### Get existing dashboards
gcloud monitoring dashboards list --project="${project}" --format=json \
  | jq 'del(.[].etag, .[].name)' > dashboards.json

### Split each dashboard into a seperate file
for i in $(seq "$(jq '.|length' dashboards.json)"); do \
    j=$(( "$i" - 1 )); \
    jq ".[$j]" dashboards.json > "dashboard-${j}.json";  \
done

### Convert display names to file names
for file in dashboard-*.json; do \
  name=$(jq -r '.displayName' "${file}" | sed 's/ /-/g;s#/##g' | tr -s '-')
  mv "${file}" "${name}.json"; \
done
